### ISSUE TITLE
LANG_014 App Icon

### ISSUE THREAD

**Issue by chsheahan** [sw19-tug/morning04#24]
Acceptance Criteria:
-Find/Make aesthetically pleasing icon
-Implement to be visible as app icon

**Comment by trimmell** [comment]
Icon used with free license: https://icons8.de/icon/set/dictionary/androidL
Android app launcher icon generator: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

**Comment by schleidi** [comment]
bug with icon in newer Android versions fixed
