### ISSUE TITLE
LANG_015 UI Design

### ISSUE THREAD

**Issue by chsheahan** [sw19-tug/morning04#25]
Acceptance Criteria:
-Concise menu with all user options
-Options are user friendly (naming, format, etc.)
-Back button to return to menu in all features

**Comment by trimmell** [comment]
- android.support.v7.widget.Toolbar - ActionBar added to all activities and layout-sheets.
- Back-Button implemented for all activities. 
- Reworked menu including multilanguage-support string resources.
- Added search box to several layout-sheets. 
- Implemented search-box for Learning-View
